### ISSUE TITLE
request fix typo 

### ISSUE THREAD

**Issue by EeeUnS** [YiHoze/HzGuide#1]
wiki page에서   `https://yihoze.github.io/에서  `로 붙어있어서  `https://yihoze.github.io/에서` 로 리다이렉트 됩니다.
`https://yihoze.github.io/ 에서` 이렇게 띄우면 될겁니다.

정말 사소한건데 wiki는 클론은 되지만 pr넣는 방법이없어서 이슈로 요청드립니다.

**Comment by YiHoze** [comment]
무슨 위키 페이지요?

**Comment by EeeUnS** [comment]
https://github.com/YiHoze/HzGuide/wiki

요 페이지 입니다!

**Comment by YiHoze** [comment]
까맣게 잊고 있었는데 ... 아무튼 고쳤습니다. ^^
